library_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lms/', include('lms.urls')),
    path('', RedirectView.as_view(url='lms/', permanent=True))
]

lms/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'lms'
urlpatterns = [
    path('', views.index, name='index'),
    path('search-book', views.search_book, name='search-book'),
    path('login-admin', views.login_admin, name='admin-login'),
    path('admin', RedirectView.as_view(url='admin/dashboard', permanent=True)),
    path('admin/dashboard', views.admin_dashboard, name='admin-dashboard'),
    path('admin/borrow-return', views.admin_borrow_return, name='admin-borrow-return'),
    path('admin/add-borrow-return', views.admin_add_borrow_return, name='admin-add-borrow-return'),
    path('admin/book', views.admin_book, name='admin-book'),
    path('admin/author', views.admin_author, name='admin-author'),
    path('admin/publisher', views.admin_publisher, name='admin-publisher'),
    path('admin/borrower', views.admin_borrower, name='admin-borrower'),
    path('admin/borrow-log', views.admin_borrow_log, name='admin-borrow-log'),
    path('admin/borrow-log/<int:month>/<int:year>', views.admin_borrow_log_with_date, name='admin-borrow-log-with-date'),
    path('admin/borrow-log-download/<int:month>/<int:year>', views.admin_borrow_log_pdf, name='admin-borrow-log-pdf'),
    path('admin/category', views.admin_category, name='admin-category'),
    path('admin/logout', views.admin_logout, name='admin-logout'),
    path('admin/book/add', views.admin_add_book, name='admin-add-book'),
    path('admin/book/detail/<int:book_id>', views.admin_book_detail, name='admin-book-detail'),
    path('admin/book/update/<int:book_id>', views.admin_update_book, name='admin-update-book'),
    path('admin/book/delete/<int:book_id>', views.admin_delete_book, name='admin-delete-book'),
    path('admin/borrower/add', views.admin_add_borrower, name='admin-add-borrower'),
    path('admin/borrower/detail/<int:borrower_id>', views.admin_borrower_detail, name='admin-borrower-detail'),
    path('admin/borrower/update/<int:borrower_id>', views.admin_update_borrower, name='admin-update-borrower'),
    path('admin/borrower/delete/<int:borrower_id>', views.admin_delete_borrower, name='admin-delete-borrower'),
    path('admin/borrower/member-card/<int:borrower_id>', views.admin_member_card, name='admin-member-card'),
    path('admin/author/add', views.admin_add_author, name='admin-add-author'),
    path('admin/author/detail/<int:author_id>', views.admin_author_detail, name='admin-author-detail'),
    path('admin/author/update/<int:author_id>', views.admin_update_author, name='admin-update-author'),
    path('admin/author/delete/<int:author_id>', views.admin_delete_author, name='admin-delete-author'),
    path('admin/publisher/add', views.admin_add_publisher, name='admin-add-publisher'),
    path('admin/publisher/detail/<int:publisher_id>', views.admin_publisher_detail, name='admin-publisher-detail'),
    path('admin/publisher/update/<int:publisher_id>', views.admin_update_publisher, name='admin-update-publisher'),
    path('admin/publisher/delete/<int:publisher_id>', views.admin_delete_publisher, name='admin-delete-publisher'),
    path('admin/category/add', views.admin_add_category, name='admin-add-category'),
    path('admin/category/update/<int:category_id>', views.admin_update_category, name='admin-update-category'),
    path('admin/category/delete/<int:category_id>', views.admin_delete_category, name='admin-delete-category'),
    path('admin/borrow-log/delete/<int:id>', views.admin_delete_borrow_log, name='admin-delete-borrow-log'),
]

lms/models.py
from datetime import datetime
from django.db import models


# Create your models here.
class Author(models.Model):
    author_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)

    # Buat index supaya lookup lebih efisien
    # See https://stackoverflow.com/questions/45328826/django-model-fields-indexing
    class Meta():
        indexes = [
            models.Index(fields=['name'])
        ]
    
    def __str__(self):
        return self.name


class Publisher(models.Model):
    publisher_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)

    # Buat index supaya lookup lebih efisien
    # See https://stackoverflow.com/questions/45328826/django-model-fields-indexing
    class Meta():
        indexes = [
            models.Index(fields=['name'])
        ]
    
    def __str__(self):
        return self.name


class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Borrower(models.Model):
    borrower_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    contact = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name} - {self.contact}'


class Book(models.Model):
    book_id = models.CharField(max_length=15, primary_key=True)
    title = models.CharField(max_length=100)
    year_published = models.IntegerField()
    quantity = models.IntegerField(default=0)
    location = models.CharField(max_length=100)
    
    author_id = models.ManyToManyField(Author, related_name='books')
    publisher_id = models.ForeignKey(Publisher, on_delete=models.SET_NULL, related_name='books', null=True)
    category_id = models.ManyToManyField(Category, related_name='books')

    def __str__(self):
        return f'{self.book_id} - {self.title} - {self.location}'


class BorrowBook(models.Model):
    borrower_id = models.ForeignKey(Borrower, on_delete=models.CASCADE, related_name='borrow_table')
    book_id = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='borrow_table')
    
    def __str__(self):
        return f'Borrower ID: {self.borrower_id} - Book ID: {self.book_id}'


# class BookCategory(models.Model):
#     category_id = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='book_category')
#     book_id = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='book_category')

#     def __str__(self):
#         return f'Category ID: {self.category_id} Book ID: {self.book_id}'


# class BookAuthor(models.Model):
#     author_id = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='book_author')
#     book_id = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='book_author')

#     def __str__(self):
#         return f'Author ID: {self.author_id} Book ID: {self.book_id}'


class BorrowLog(models.Model):
    log_description = models.CharField(max_length=100)
    log_time = models.DateTimeField(default=datetime.now)
    # Either BORROW or RETURN
    activity = models.CharField(max_length=6, default='BORROW')
    book_id = models.ForeignKey(Book, on_delete=models.SET_NULL, related_name='borrow_log', null=True)
    borrower_id = models.ForeignKey(Borrower, on_delete=models.SET_NULL, related_name='borrow_log', null=True)

    def __str__(self):
        return self.log_description

class Admin(models.Model):
    admin_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.username

lms/views.py
from django.contrib import messages
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.db.models import F
from django.db import transaction 

from .models import Author, Book, Borrower, BorrowLog, Category, Publisher, BorrowBook, BorrowLog, Admin
from .utils import render_borrow_log_to_pdf

import datetime
import calendar
# Decorators
# @gfg_decorator
# def hello_decorator():
#     print("Gfg")

# '''Above code is equivalent to -

# def hello_decorator():
#     print("Gfg")
    
# hello_decorator = gfg_decorator(hello_decorator)'''

# Create your views here.
def index(request):
    """Visitor index page"""
    return render(request, 'lms/index.html', {
        # Navigation show `admin` or `login` depending if session exist or not
        'logged_in': (request.session['logged_in'] if 'logged_in' in request.session
            else False),
    })


def search_book(request):
    """View to search for books"""
    return render(request, 'lms/search-book.html', {
        # Navigation show `admin` or `login` depending if session exist or not
        'logged_in': (request.session['logged_in'] if 'logged_in' in request.session
            else False),
        'books': Book.objects.all(),
    })


def login_admin(request):
    """Admin login view"""
    if request.method == 'POST':
        if Admin.objects.filter(username=request.POST['username'].strip(), 
                                password=request.POST['password']).exists():
            request.session['logged_in'] = True
            return HttpResponseRedirect(reverse('lms:admin-dashboard'))
        else:
            messages.warning(request, 'Invalid username or password')
            return HttpResponseRedirect(reverse('lms:admin-login'))
    
    return render(request, 'lms/admin-login.html')


def check_login(func):
    """Decorator use to validate if admin is login or not
    to prevent unwanted visitor
    """
    def wrapper(*args, **kwargs):
        request = args[0]
        # Prevent random visitor from visiting the page
        if 'logged_in' not in request.session:
            return HttpResponseRedirect(reverse('lms:admin-login'))
        return func(*args, **kwargs)

    return wrapper

@check_login
def admin_dashboard(request):
    """Render dashboard"""
    now = datetime.datetime.now()
    current_month = now.month
    current_year = now.year
    book_count = Book.objects.all().count()
    borrower_count = Borrower.objects.all().count()
    author_count = Author.objects.all().count()
    borrowed_count = BorrowLog.objects.filter(
        activity='BORROW', 
        log_time__month=current_month, 
        log_time__year=current_year
    ).count()
    returned_count = BorrowLog.objects.filter(
        activity='RETURN', 
        log_time__month=current_month, 
        log_time__year=current_year
    ).count()
    return render(request, 'lms/admin/dashboard.html', {
        'dashboard_nav': 'active-nav',
        'book_count': book_count,
        'borrower_count': borrower_count,
        'author_count': author_count,
        'borrowed_count': borrowed_count,
        'returned_count': returned_count,
    })


@check_login
def admin_borrow_return(request):
    """Render borrow or return pages"""
    return render(request, 'lms/admin/borrow-return.html', {
        'borrow_return_nav': 'active-nav',
    })


@check_login
def admin_add_borrow_return(request):
    """Render borrow or return pages"""
    if request.method == 'POST':
        book_id = request.POST['book-id']
        borrower_id = request.POST['borrower-id']
        book = get_object_or_404(Book.objects.select_for_update(), pk=book_id)
        borrower = get_object_or_404(Borrower, pk=int(borrower_id))

        # Check if the book and borrower exist in the borrow book
        # If it exist, then it already borrowed, it follow that borrower must return
        # Else borrow the book
        borrow_book_exist = BorrowBook.objects.select_for_update().filter(book_id=book, borrower_id=borrower_id).exists()
        with transaction.atomic():
            if borrow_book_exist:
                # RETURN LOGIC
                # Delete the book in BorrowBook and log it into BorrowLog
                # Also increase the quantity on the Book table
                
                # Delete the table that represent borrowed book of that value
                borrow_book = get_object_or_404(BorrowBook, book_id=book, borrower_id=borrower)
                borrow_book.delete()

                borrow_log = BorrowLog.objects.create(
                    log_description=f'{borrower.name} returns {book.title}',
                    activity='RETURN',
                    book_id=book,
                    borrower_id=borrower
                )
                # Increase the quantity by 1
                book.quantity = F('quantity') + 1
                book.save()
                return HttpResponseRedirect(reverse('lms:admin-borrow-return'))
            else:
                # BORROW LOGIC
                # Add the book to BorrowBook and log it into BorrowLog
                # Also decrease the quantity on book table
                if not book.quantity <= 0:
                    book.quantity = F('quantity') - 1
                    book.save()
                else:
                    return HttpResponseBadRequest('The current book quantity is zero, fix the quantity first')

                new_borrow_book = BorrowBook.objects.create(
                    book_id=book,
                    borrower_id=borrower
                )
                borrow_log = BorrowLog.objects.create(
                    log_description=f'{borrower.name} borrows {book.title}',
                    activity='BORROW',
                    book_id=book,
                    borrower_id=borrower
                )
                return HttpResponseRedirect(reverse('lms:admin-borrow-return'))
    return HttpResponseRedirect(reverse('lms:admin-borrow-return'))


@check_login
def admin_book(request):
    """Render admin's book view"""
    return render(request, 'lms/admin/book.html', {
        'books': Book.objects.all(),
        'book_nav': 'active-nav',
    })


@check_login
def admin_author(request):
    """Render admin's author view"""
    # Prevent the random visitor to visit admin page
    if 'logged_in' not in request.session:
        return HttpResponseRedirect(reverse('lms:admin-login'))

    return render(request, 'lms/admin/author.html', {
        'authors': Author.objects.all(),
        'author_nav': 'active-nav',
    })


@check_login
def admin_publisher(request):
    """Render admin's publisher view"""
    return render(request, 'lms/admin/publisher.html', {
        'publishers': Publisher.objects.all(),
        'publisher_nav': 'active-nav',
    })


@check_login
def admin_borrower(request):
    """Render admin's borrower view"""
    return render(request, 'lms/admin/borrower.html', {
        'borrowers': Borrower.objects.all(),
        'borrower_nav': 'active-nav'
    })


@check_login
def admin_category(request):
    """Render admin's category view"""
    return render(request, 'lms/admin/category.html', {
        'categories': Category.objects.all(),
        'category_nav': 'active-nav',
    })


@check_login
def admin_borrow_log(request):
    """Render admin's book log view"""
    year_list = BorrowLog.objects.distinct().values_list("log_time__year", flat=True)

    return render(request, 'lms/admin/borrow-log.html', {
        'borrow_logs': BorrowLog.objects.all().order_by('-log_time'),
        'borrow_log_nav': 'active-nav',
        'years': year_list,
    })

@check_login
def admin_borrow_log_with_date(request, month, year):
    """Render admin's book log view with chosen date"""
    year_list = BorrowLog.objects.distinct().values_list("log_time__year", flat=True)

    return render(request, 'lms/admin/borrow-log.html', {
        'borrow_logs': BorrowLog.objects.all()\
            .filter(log_time__month=month, log_time__year=year)\
            .order_by('-log_time'),
        'borrow_log_nav': 'active-nav',
        'month': month,
        'selected_year': year,
        'years': year_list,
    })


@check_login
def admin_borrow_log_pdf(request, month, year):
    """Download the chosen date borrow log pdf"""
    template_name = 'lms/admin/report-borrow.html'
    pdf_name = f'borrow_log {month}_{year}.pdf'
    borrowed_count = BorrowLog.objects.filter(
        activity='BORROW', 
        log_time__month=month, 
        log_time__year=year
    ).count()
    returned_count = BorrowLog.objects.filter(
        activity='RETURN', 
        log_time__month=month, 
        log_time__year=year
    ).count()

    return render_borrow_log_to_pdf(template_name, pdf_name, {
        'borrow_logs': BorrowLog.objects.all()\
            .filter(log_time__month=month, log_time__year=year)\
            .order_by('log_time'),
        'month_name': calendar.month_name[month],
        'year': year,
        'borrow_count': borrowed_count,
        'return_count': returned_count,
    })

@check_login
def admin_logout(request):
    """Run a logout admin logic"""
    # Prevent the random visitor to visit admin page
    if 'logged_in' not in request.session:
        return HttpResponseRedirect(reverse('lms:admin-login'))
    
    try:
        del request.session['logged_in']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('lms:admin-login'))


def get_or_create_author(author_name):
    """Get or create the author object depending if the author name exist or not"""
    return (
        Author.objects.get(name=author_name) if
        Author.objects.filter(name=author_name).exists() and author_name.strip() != ''
        else Author.objects.create(name=author_name)
    )

def get_or_create_category(category_name):
    """Get or create the category object depending if the category name exist or not"""
    return (

lms/templates/lms/admin/author-add.html
{% extends 'lms/admin/admin-layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block main %}
    <form class="form" action="{% url 'lms:admin-add-author' %}" method="POST">
        {% csrf_token %}

        <h2>Add Author</h2>
        <div class="form-control">
            <label>Author name</label>
            <input type="text" name="name" required>
        </div>
        <div class="form-control">
            <input type="submit" value="Add">
        </div>
    </form>
{% endblock %}

lms/templates/lms/admin/author-update.html
{% extends 'lms/admin/admin-layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block main %}
    <form class="form" action="{% url 'lms:admin-update-author' author.author_id %}" method="POST">
        {% csrf_token %}

        <h2>Update Author</h2>
        <div class="form-control">
            <label>Author name</label>
            <input type="text" name="name" value="{{ author.name }}" required>
        </div>
        <div class="form-control">
            <input type="submit" value="Update">
        </div>
    </form>
{% endblock %}

lms/templates/lms/admin/book-add.html
{% extends 'lms/admin/admin-layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        .form .form-control input:focus-visible,
        .form .form-control select:focus-visible,
        .form .form-control textarea:focus-visible {
            outline: none;
            box-shadow: none;
        }
    </style>
{% endblock %}

{% block head-js %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
{% endblock %}

{% block main %}
    <form class="form" action="{% url 'lms:admin-add-book' %}" method="POST">
        {% csrf_token %}

        <h2>Add Book</h2>
        <div class="form-control">
            <label>Book ID (ISBN)</label>
            <input type="text" name="id" required>
        </div>
        <div class="form-control">
            <label>Title</label>
            <input type="text" name="title" required>
        </div>
        <div class="form-control">
            <label>Year</label>
            <input type="number" name="year" required>
        </div>
        <div class="form-control">
            <label>Quantity</label>
            <input type="number" name="quantity" required>
        </div>
        <div class="form-control">
            <label>Location</label>
            <input type="text" name="location" required>
        </div>
        <div class="form-control">
            <label>Author</label>
            <select class="tag-select" name="author" multiple="multiple">
                {% for author in authors %}
                    <option value="{{ author.name }}">{{ author.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-control">
            <label>Publisher</label>
            <select class="tag-select" name="publisher" required>
                {% for publisher in publishers %}
                    <option value="{{ publisher.name }}">{{ publisher.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-control">
            <label>Category</label>
            <select class="tag-select" name="category" multiple="multiple" required>
                {% for category in categories %}
                    <option value="{{ category.name }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-control">
            <input type="submit" value="Add">
        </div>
    </form>
{% endblock %}

{% block bottom-js %}
    <script type="text/javascript">
        // let availableOption = '';

        $(document).ready(function() {
            $('.tag-select').select2({
                tags: true,
                tokenSeperators: [',', ' ']
            });
        });
        
        // $('.tag-select').on('select2:open', function (e) {
        //     // Store the available option
        //     availableOption = Array.prototype.slice.call(e.target.children).map(x => x.value);
        // });

        // $('.tag-select').on('select2:select', function (e) {
        //     let test = Array.prototype.slice.call(e.target.children).map(x => x.value);
        //     console.log(test);
        // });
    </script>
{% endblock %}

lms/templates/lms/admin/book-detail.html
{% extends 'lms/admin/admin-layout.html' %}
{% load static %}

{% block css %}
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'js-table/jstable.css' %}"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block main %}
    <h1>{{ book.title }}</h1>
    <h3 class="author">
        Author:
        {% for author in book.author_id.all %}
            <a href="{% url 'lms:admin-author-detail' author.author_id %}" class="erase-link-default link-color">{{ author.name }}</a>
            {% if not forloop.last %}<span>, </span>{% endif %}
            {% empty %}
                Unknown
        {% endfor %}
    </h3>
    <h2>Details</h2>
    <section class="details">
        <p class="info">ISBN</p>
        <p class="detail">{{ book.book_id }}</p>
        <p class="info">Quantity</p>
        <p class="detail">{{ book.quantity }}</p>
        <p class="info">Year Published</p>
        <p class="detail">{{ book.year_published }}</p>
        <p class="info">Location</p>
        <p class="detail">{{ book.location }}</p>
        <p class="info">Publisher</p>
        <p class="detail">{{ book.publisher_id }}</p>
        <p class="info">Category</p>
        <p class="detail">
            {% for category in book.category_id.all %}
                <span class="muted-tag">{{ category.name }}</span>
            {% endfor %}
        </p>
        <p class="info">Current Borrower</p>
        <p class="detail">
            {% for borrow_table in book.borrow_table.all %}
                <a class="button update"
                    href="{% url 'lms:admin-borrower-detail' borrow_table.borrower_id.borrower_id %}">
                    {{ borrow_table.borrower_id.name }}
                </a>
                {% empty %}
                -
            {% endfor %}
        </p>
    </section>
{% endblock %}

lms/templates/lms/admin/borrow-log.html
{% extends 'lms/admin/admin-layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'js-table/jstable.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/table-main.css' %}">
{% endblock %}
{% block head-js %}
    <script type="text/javascript" src="{% static 'js-table/jstable.min.js' %}"></script>
{% endblock %}

{% block main %}
    <h1 class="table-title">Search Borrow Log</h1>
    <div class="table-action">
        <div>
            Month
            <select id="month">
                <option value="1" {%if month == 1 %}selected{% endif %}>1</option>
                <option value="2" {%if month == 2 %}selected{% endif %}>2</option>
                <option value="3" {%if month == 3 %}selected{% endif %}>3</option>
                <option value="4" {%if month == 4 %}selected{% endif %}>4</option>
                <option value="5" {%if month == 5 %}selected{% endif %}>5</option>
                <option value="6" {%if month == 6 %}selected{% endif %}>6</option>
                <option value="7" {%if month == 7 %}selected{% endif %}>7</option>
                <option value="8" {%if month == 8 %}selected{% endif %}>8</option>
                <option value="9" {%if month == 9 %}selected{% endif %}>9</option>
                <option value="10" {%if month == 10 %}selected{% endif %}>10</option>
                <option value="11" {%if month == 11 %}selected{% endif %}>11</option>
                <option value="12" {%if month == 12 %}selected{% endif %}>12</option>
            </select>
            <span class="margin-left10"></span>
            Year
            <select id="year">
                {% for year in years %}
                    <option value="{{ year }}" {%if selected_year == year %}selected{% endif %}>{{ year }}</option>
                {% endfor %}
            </select>
            <span class="margin-left10"></span>
            <a id="go-to-url" href="#" class="erase-link-default button add">Go</a>
            <a id="download" href="{%if month and selected_year %} 
            {% url 'lms:admin-borrow-log-pdf' month selected_year %}
            {% else %} # {% endif %}" class="erase-link-default button update">Download</a>
        </div>
        
    </div>
    <table id="basic">
        <thead>
            <tr>
                <th>Log description</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for borrow_log in borrow_logs %}
                <tr>
                    <td>{{ borrow_log.log_description }}</td>
                    <td>{{ borrow_log.log_time }}</td>
                    <td>
                        <a class="button warning erase-link-default" href="{% url 'lms:admin-delete-borrow-log' borrow_log.id %}">
                            Delete
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block bottom-js %}
    <script type="text/javascript">
        let myTable = new JSTable("#basic");
        let borrow_log_url = '{% url 'lms:admin-borrow-log' %}';

        document.querySelector('#go-to-url').onclick = function() {
            let month = document.querySelector('#month').value;
            let year = document.querySelector('#year').value;
            location.href = `${borrow_log_url}/${month}/${year}`;
        };
    </script>
{% endblock %}

lms/templates/lms/admin/borrower-update.html
{% extends 'lms/admin/admin-layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block main %}
    <form class="form" action="{% url 'lms:admin-update-borrower' borrower.borrower_id %}" method="POST">
        {% csrf_token %}

        <h2>Update Borrower</h2>
        <div class="form-control">
            <label>Borrower Name</label>
            <input type="text" name="name" value="{{ borrower.name }}" required>
        </div>
        <div class="form-control">
            <label>Address</label>
            <input type="text" name="address" value="{{ borrower.address }}" required>
        </div>
        <div class="form-control">
            <label>Contact</label>
            <input type="text" name="contact" value="{{ borrower.contact }}" required>
        </div>
        <div class="form-control">
            <input type="submit" value="Update">
        </div>
    </form>
{% endblock %}

- Data excel
- Alasan milih data ato kasus tersebut
- Algoritma Python ato Knimw
- Draft dari artikel/jurnalnya

lms/templates/lms/admin/category-add.html
{% extends 'lms/admin/admin-layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block main %}
    <form class="form" action="{% url 'lms:admin-add-category' %}" method="POST">
        {% csrf_token %}

        <h2>Add Category</h2>
        <div class="form-control">
            <label>Category name</label>
            <input type="text" name="name" required>
        </div>
        <div class="form-control">
            <input type="submit" value="Add">
        </div>
    </form>
{% endblock %}

lms/templates/lms/admin/category-update.html
{% extends 'lms/admin/admin-layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block main %}
    <form class="form" action="{% url 'lms:admin-update-category' category.category_id %}" method="POST">
        {% csrf_token %}

        <h2>Update Category</h2>
        <div class="form-control">
            <label>Category name</label>
            <input type="text" name="name" value="{{ category.name }}" required>
        </div>
        <div class="form-control">
            <input type="submit" value="Update">
        </div>
    </form>
{% endblock %}

lms/templates/lms/admin/category.html
{% extends 'lms/admin/admin-layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'js-table/jstable.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/table-main.css' %}">
{% endblock %}
{% block head-js %}
    <script type="text/javascript" src="{% static 'js-table/jstable.min.js' %}"></script>
{% endblock %}

{% block main %}
    <h1 class="table-title">Search Category</h1>
    <a class="button erase-link-default margin-left10" 
       href="{% url 'lms:admin-add-category' %}">
       Add
    </a>

    <table id="basic">
        <thead>
            <tr>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
                <tr>
                    <td>{{ category.name }}</td>
                    <td>
                        <a class="button update erase-link-default" href="{% url 'lms:admin-update-category' category.category_id %}">
                            Update
                        </a>
                        <a class="button warning erase-link-default" href="{% url 'lms:admin-delete-category' category.category_id %}">
                            Delete
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block bottom-js %}
    <script type="text/javascript">
        let myTable = new JSTable("#basic");
    </script>
{% endblock %}